server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dummy_banking_backend_db?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: s9yq67Uc6CHinCj8gcj6+X5ihq3SE3pO4J7f7Ablt3U=
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
