spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_dummy_backend_db?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  jwt:
    secret: s9yq67Uc6CHinCj8gcj6+X5ihq3SE3pO4J7f7Ablt3U=
    expiration-ms: 86400000
